# Generated by Django 4.0.3 on 2022-03-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('capa', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'managed': True,
            },
        ),
    ]
