# Generated by Django 4.0.3 on 2022-03-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_reserva_validade_reserva_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='ativo',
        ),
    ]
