# Generated by Django 4.0.3 on 2022-03-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_reserva_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='reservado',
            field=models.BooleanField(default=True),
        ),
    ]
